/*
 * Copyright (c) 2022-2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import deviceInfo from '@ohos.deviceInfo';
import deviceManager from '@ohos.distributedDeviceManager';
import Logger from '../common/Logger';
import { RemoteDeviceModel } from '../model/RemoteDeviceModel';
import router from '@ohos.router';
import { FilterOption } from '../pages/FilterOption';
import { ListDeviceView } from '../pages/ListDeviceView';
import { getGlobalObject, setGlobalObject } from '../common/GlobalThis'
import { TitleBar } from '../common/TitleBar';

class optionsType {
  url: string = 'pages/FilterOption'
}

const TAG: string = "[DeviceManager]"

@Entry
@Component
struct DeviceManager {
  @StorageLink('localDevice') localDevice: deviceManager.DeviceBasicInfo = {
    deviceId: "",
    deviceName: "",
    deviceType: "",
    networkId: ""
  };
  @State isShowLoading: boolean = false;
  @State indexWidth: string = '100%';
  @StorageLink('trustedDeviceList') trustedDeviceList: Array<deviceManager.DeviceBasicInfo> =
    new Array<deviceManager.DeviceBasicInfo>();
  @StorageLink('discoverDeviceList') discoverDeviceList: Array<deviceManager.DeviceBasicInfo> =
    new Array<deviceManager.DeviceBasicInfo>();
  @State isSupportRange: boolean = false;
  @State isAllowDiscovered: boolean = true;
  @State isLocalDeviceActive: boolean = false;
  @State filterOption: string = '';
  @State isDiscovering: boolean = false;
  scroller: Scroller = new Scroller();
  @State remoteDeviceModel: RemoteDeviceModel = new RemoteDeviceModel()

  async routeFilterOptionPage() {
    let options = new optionsType();
    try {
      await router.pushUrl(options);
    } catch (err) {
      Logger.info(TAG, `fail callback, code: ${err.code}, msg: ${err.msg}`);
    }
  }

  getDeviceTypeIcon(deviceType: string): Resource {
    if (deviceType == "tablet") {
      return $r('app.media.ic_pad');
    } else if (deviceType == "phone") {
      return $r('app.media.ic_phone');
    } else if (deviceType == "default") {
      return $r('app.media.ic_pc');
    } else {
      return $r('app.media.ic_pc');
    }
  }

  async aboutToAppear() {
    await this.remoteDeviceModel.createDeviceManager();
    try {
      Logger.info(TAG, `local deviceType:` + deviceInfo.deviceType);
      let deviceTypeName: string = getContext(this).resourceManager.getStringSync($r('app.string.device_type').id);
      let authFormName: string = getContext(this).resourceManager.getStringSync($r('app.string.auth_form').id);
      let isOnlineName: string = getContext(this).resourceManager.getStringSync($r('app.string.is_online').id);
      let isTrustedName: string = getContext(this).resourceManager.getStringSync($r('app.string.is_trusted').id);
      let rangeName: string = getContext(this).resourceManager.getStringSync($r('app.string.range').id);

      setGlobalObject('deviceTypeName', deviceTypeName)
      setGlobalObject('authFormName', authFormName)
      setGlobalObject('isOnlineName', isOnlineName)
      setGlobalObject('isTrustedName', isTrustedName)
      setGlobalObject('rangeName', rangeName)
      let filterOptions: Map<string, number> = new Map();
      filterOptions.set(deviceTypeName, 0)
      filterOptions.set(authFormName, 0)
      filterOptions.set(isOnlineName, 0)
      filterOptions.set(isTrustedName, 0)
      filterOptions.set(rangeName, 0)
      setGlobalObject('filterOptions', filterOptions)
      this.getFilterOption();
    } catch (error) {
      Logger.error(`getStringByNameSync failed, error code: ${error.code}, message: ${error.message}.`);
    }
  }

  getFilterOption() {
    let filterOptionList = new Map<string, Array<string>>();
    filterOptionList.set(getGlobalObject('deviceTypeName') as string, getGlobalObject('DeviceTypeItemList') as string[])
    filterOptionList.set(getGlobalObject('authFormName') as string, getGlobalObject('AuthFormItemList') as string[])
    filterOptionList.set(getGlobalObject('isOnlineName') as string, getGlobalObject('IsOnlineItemList') as string[])
    filterOptionList.set(getGlobalObject('isTrustedName') as string, getGlobalObject('IsTrustedItemList') as string[])
    filterOptionList.set(getGlobalObject('rangeName') as string, getGlobalObject('RangeItemList') as string[])
    this.filterOption = '';
    let tempMap = getGlobalObject('filterOptions') as Map<string, number>
    tempMap.forEach((value: number, key: string, map: Map<string, number>) => {
      if (value !== 0) {
        this.filterOption += (filterOptionList.get(key) as Array<string>)[value] + ' ';
      }
    })
    Logger.info(TAG, 'this.filterOption = ' + JSON.stringify(this.filterOption));
  }

  onPageShow() {
    Logger.info(TAG, 'onPageShow');
  }

  build() {
    Row() {
      Scroll(this.scroller) {
        Column() {
          Stack() {
            Row() {
              TitleBar({ title: $r('app.string.device_manager'), hasBackPress: true })
            }
          }.width('100%')

          Column() {
            Row() {
              Image(this.getDeviceTypeIcon(this.localDevice!.deviceType))
                .width(24)
                .height(24)
              Text(this.localDevice!.deviceName)
                .fontSize(16)
                .fontColor('#182431')
                .fontFamily('HarmonyHeiTi-Medium')
                .fontWeight(500)
                .margin({ left: 8 })
            }
            .width('100%')
            .height(48)

            Divider()
              .color('#182431')
              .opacity(0.05)

            Row() {
              Text($r('app.string.support_range'))
                .fontSize(16)
                .fontColor('#182431')
                .fontFamily('HarmonyHeiTi-Medium')
                .fontWeight(500)
              Blank()
              Toggle({ type: ToggleType.Switch, isOn: this.isSupportRange })
                .selectedColor('#007DFF')
                .switchPointColor('#FFFFFF')
                .onChange((isOn: boolean) => {
                  Logger.info(TAG, 'Component status:' + isOn);
                  this.isSupportRange = isOn;
                  this.remoteDeviceModel.setIsSupportRange(this.isSupportRange);
                  if (this.isAllowDiscovered) {
                    this.isAllowDiscovered = false;
                    let gThis = this;
                    setTimeout(() => {
                      gThis.isAllowDiscovered = true;
                    }, 1000);
                  }
                })
            }.width('100%')
            .height(48)

            Divider()
              .color('#182431')
              .opacity(0.05)

            Row() {
              Text($r('app.string.allowed_discovered'))
                .fontSize(16)
                .fontColor('#182431')
                .fontFamily('HarmonyHeiTi-Medium')
                .fontWeight(500)
              Blank()
              Toggle({ type: ToggleType.Switch, isOn: this.isAllowDiscovered })
                .selectedColor('#007DFF')
                .switchPointColor('#FFFFFF')
                .onChange((isOn: boolean) => {
                  Logger.info(TAG, 'Component status:' + isOn);
                  this.isAllowDiscovered = isOn;
                })
            }.width('100%')
            .height(48)
          }.borderRadius(24)
          .backgroundColor('#FFFFFF')
          .padding({ left: 12, right: 12, top: 4, bottom: 4 })
          .width('100%')

          Column() {
            Row() {
              Text($r('app.string.trusted_devices'))
                .fontSize(14)
                .fontColor('#182431')
                .fontFamily('HarmonyHeiTi-Medium')
                .lineHeight(19)
                .margin({ left: 12, top: 19, bottom: 10 })
                .opacity(0.6)

              Blank()

              Text($r('app.string.refresh'))
                .fontSize(14)
                .fontColor('#007DFF')
                .fontFamily('HarmonyHeiTi-Medium')
                .lineHeight(19)
                .margin({ left: 12, top: 19, bottom: 10, right: 12 })
                .onClick(() => {
                  this.remoteDeviceModel.getTrustedDeviceList();
                  this.isShowLoading = true;
                  let gThis = this;
                  setTimeout(() => {
                    gThis.isShowLoading = false;
                  }, 3000);
                })
                .visibility(this.isShowLoading ? Visibility.None : Visibility.Visible)
              LoadingProgress()
                .color('#007DFF')
                .width(24)
                .height(24)
                .margin({ left: 12, top: 19, bottom: 10, right: 12 })
                .visibility(this.isShowLoading ? Visibility.Visible : Visibility.None)
            }.width('100%')

            List() {
              ForEach(this.trustedDeviceList, (item: deviceManager.DeviceBasicInfo, index: number) => {
                ListItem() {
                  Column() {
                    ListDeviceView({ deviceInfo: item, visible: Visibility.Visible })
                    Divider()
                      .color('#182431')
                      .opacity(0.05)
                      .visibility(index == this.trustedDeviceList.length - 1 ? Visibility.None : Visibility.Visible)
                  }
                }
              }, (item: deviceManager.DeviceBasicInfo) => JSON.stringify(item))
            }
            .width('100%')
            .borderRadius(24)
            .padding({ left: 12, right: 12, top: 4, bottom: 4 })
            .backgroundColor('#FFFFFF')
          }.visibility(this.trustedDeviceList.length == 0 ? Visibility.None : Visibility.Visible)

          Column() {
            Row() {
              Text($r('app.string.usable_devices'))
                .fontSize(14)
                .fontColor('#182431')
                .fontFamily('HarmonyHeiTi-Medium')
                .lineHeight(19)
                .opacity(0.6)
                .margin({ left: 12, top: 19, bottom: 10 })

              Blank()

              Text(this.isDiscovering == false ? $r('app.string.discover') : $r('app.string.stop'))
                .fontSize(14)
                .fontColor(this.isDiscovering == false ? '#007DFF' : '#FA2A2D')
                .lineHeight(19)
                .margin({ left: 12, top: 19, bottom: 10, right: 12 })
                .onClick(() => {
                  if (this.isDiscovering) {
                    this.remoteDeviceModel.stopDeviceDiscovery();
                  } else {
                    this.remoteDeviceModel.startDeviceDiscovery();
                  }
                  this.isDiscovering = !this.isDiscovering;
                })
            }.width('100%')
          }.width('100%')

          Column() {
            Column() {
              Row() {
                Text($r('app.string.filter_options'))
                  .fontSize(16)
                  .fontColor('#182431')
                  .fontFamily('HarmonyHeiTi-Medium')
                  .fontWeight(500)
                Blank()
                Row() {
                  Text(this.filterOption)
                    .fontSize(14)
                    .fontColor('#182431')
                    .fontFamily('HarmonyHeiTi')
                    .opacity(0.6)
                    .margin({ left: 12 })
                    .textOverflow({ overflow: TextOverflow.Ellipsis })
                    .maxLines(1)
                    .fontWeight(400)
                  Image($r('app.media.ic_arrow'))
                    .width(12)
                    .height(24)
                    .margin({ left: 8 })
                }
              }.onClick(() => {
                if (deviceInfo.deviceType == 'tablet') {
                  this.indexWidth = '50%';
                } else {
                  this.routeFilterOptionPage();
                }
              })
              .width('100%')
              .margin({ top: 12, bottom: 12 })

              Divider()
                .color('#182431')
                .opacity(0.05)
                .visibility(this.discoverDeviceList.length == 0 ? Visibility.None : Visibility.Visible)
            }.height(48)
            .alignItems(HorizontalAlign.Center)

            List() {
              ForEach(this.discoverDeviceList, (item: deviceManager.DeviceBasicInfo, index: number) => {
                ListItem() {
                  Column() {
                    ListDeviceView({ deviceInfo: item })
                    Divider()
                      .color('#182431')
                      .opacity(0.05)
                      .visibility(index == this.discoverDeviceList.length - 1 ? Visibility.None : Visibility.Visible)
                  }
                }
                .onClick(() => {
                  this.remoteDeviceModel.authenticateDevice(item);
                })
              }, (item: deviceManager.DeviceBasicInfo) => JSON.stringify(item))
            }
            .visibility(this.discoverDeviceList.length == 0 ? Visibility.None : Visibility.Visible)
            .width('100%')
          }.width('100%')
          .borderRadius(24)
          .padding({ left: 12, right: 12, bottom: 4, top: 4 })
          .backgroundColor('#FFFFFF')
        }
        .padding(12)
        .width(this.indexWidth)
      }
      .scrollBar(BarState.Off)
      .scrollable(ScrollDirection.Vertical)
      .height('100%')
      .backgroundColor('#F1F3F5')
      .align(Alignment.Top)

      Column() {
        FilterOption()
      }.visibility(this.indexWidth == '50%' ? Visibility.Visible : Visibility.None)
      .width('50%')
      .height('100%')
    }
  }
}